---
# Max fail percentage only applies to failures during the play, not previous plays

- name: Fail one host
  hosts: all
  gather_facts: no
  tasks:
    - name: Fail one host
      fail:
      when: inventory_hostname == groups['all'][0]

- name: Play with any_errors_fatal ignores previous failures
  hosts: all
  gather_facts: no
  any_errors_fatal: yes
  tasks:
    - name: Remaining hosts continue
      debug:
